options:
  merge-default-rules: false
  formatter: stylish
  max-warnings: 50

files:
  include: 'sass/**/*.s+(a|c)ss'

rules:
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-literals: 0
  no-combinators: 0
  no-ids: 0
  no-important: 0
  no-qualifying-elements: 0
  property-units: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  property-sort-order: 0
  pseudo-element: 0
  shorthand-values: 0
